steps:
# Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nih-nci-dceg-connect-stg-5519/generic-qaqc-api:$COMMIT_SHA', '-f', 'stg/', '.']
    timeout: 1200s
    #dir: 'stg'
# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nih-nci-dceg-connect-stg-5519/generic-qaqc-api:$COMMIT_SHA']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'generic-qaqc-api', '--image=gcr.io/nih-nci-dceg-connect-stg-5519/generic-qaqc-api:$COMMIT_SHA', '--cpu=2', '--memory=8192Mi', '--region=us-central1', '--service-account=qa-qc-stage@nih-nci-dceg-connect-stg-5519.iam.gserviceaccount.com']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/nih-nci-dceg-connect-stg-5519/generic-qaqc-api:$COMMIT_SHA'
