default:
  tier: stg
  project_id: "nih-nci-dceg-connect-stg-5519"
  project_number: "810867956467"
  write_to_gcs: TRUE
  bucket: gs://qaqc_reports
  box_app: NCI_BOX_GCP_CONNECT4CANCER_DEV
  box_folder: "211501237681"
  flag: ""
biospecimen:
  QC_REPORT: biospecimen
  rules_file: qc_rules_biospecimen.xlsx
recruitment:
  QC_REPORT: recruitment
  rules_file: qc_rules_recruitment.xlsx
  flag: export2box
module1:
  QC_REPORT: module1
  rules_file: qc_rules_module1.xlsx
  flag: export2box
