default:
  tier: prod
  project_id: "nih-nci-dceg-connect-prod-6d04"
  project_number: "155089172944"
  write_to_gcs: TRUE
  bucket: gs://qaqc_reports_prod
  box_app: NCI_BOX_GCP_CONNECT4CANCER_PROD
  box_folder: "211674408263"
  flag: "export2box"
biospecimen:
  QC_REPORT: biospecimen
  rules_file: qc_rules_biospecimen.xlsx
recruitment:
  QC_REPORT: recruitment
  rules_file: qc_rules_recruitment.xlsx
module1:
  QC_REPORT: module1
  rules_file: qc_rules_module1.xlsx
